### ISSUE TITLE
Type management issue in creating new subset cohort

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/DIVER#3]
As part of attempting to reproduce #2, tried to create a new subset cohort using variable A60C (first result for a search on "hallucinations"), and got an Internal Server Error reported. diverRPC test server log gives us this traceback:

```
127.0.0.1 - - [18/Feb/2022 16:59:56] "POST /api/v0/resultset/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/lib/diver/nimh-diver-be/diverRPC/diverRPC.py", line 642, in new_resultset
    return flask.jsonify(new_result_set(user, name, desc, parentset, settype,
  File "/var/lib/diver/nimh-diver-be/diverRPC/diverRPC.py", line 392, in new_result_set
    procresult = proccall_errcheck(cursor, f"API_NewResultSet_{settype}",
  File "/var/lib/diver/nimh-diver-be/diverRPC/diverRPC.py", line 185, in proccall_errcheck
    cursor.callproc(proc, procargs)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/cursors.py", line 258, in callproc
    self._query(q)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1292, "Truncated incorrect DOUBLE value: '[UNK]'")
```
Not sure why there's a casting attempt going on here or why, but definitely want to follow up.

**Comment by Viqsi** [comment]
Cannot reproduce anymore with diverweb 0.33.4, diverRPC 0.14.0, db_procs 0.12.0, db_edit 20. I want to check other "metavalue handling" bugs before I call this done, though.
